### ISSUE TITLE
plugin cannot be setup 

### ISSUE THREAD

**Issue by prox2** [situmtech/react-native#38]
It is hard to setup the plugin, Is there any proper Quip start example of how to use the plugin as the readme is not enough and not clear

**Comment by AzranAzwer** [comment]
did you find any ?

**Comment by frandieguez** [comment]
Hi @prox2,

we recently published a brand new version. Please check our updated [changelog](https://situm.com/docs/react-native-sdk-changelog/), [quick start guide](https://situm.com/docs/a-basic-react-native-app/) and [examples](https://github.com/situmtech/react-native/tree/master/example/src/examples).

We hope you find these links useful.

Do not hesitate to contact us (support@situm.com) if you need more information.

**Comment by AzranAzwer** [comment]
Hi  @frandieguez ,

I just updated the plugin and run the app.  I am getting file missing issue. screenshot added for your reference.

![Screenshot 2023-08-08 at 12 57 14 PM](https://github.com/situmtech/react-native/assets/28869406/2c104c97-26db-44f7-a578-b20470eb9922)
